[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "ffmpeg", "nodejs_22"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["pip install yt-dlp --break-system-packages"]

[start]
cmd = "node server.js"